---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting-and-quality:
    name: Formatting and Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14

      # Evaluate the devshell here so that the time reported for subsequent
      # steps that use it reflect what is actually done there.
      - name: Evaluate devShell
        run: nix develop

      - name: Format
        run: nix develop --command treefmt --fail-on-change

      - name: Clippy
        run: nix develop --command cargo clippy --all-targets

  build:
    name: Build
    needs:
      - formatting-and-quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14

      - name: Build
        run: nix develop --command wrangler deploy --dry-run
